# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: About
    url: about/
    weight: 20

  - name: Blog
    url: blog/
    weight: 30

  - name: Topics
    url: tags/
    weight: 40

  - name: Uses
    url: uses/
    weight: 50
